### PR TITLE
Added code analyzer

### PR DESCRIPTION
**Pull request by aaryan2134**
I have added the code analyzer and corrected most errors in existing files.
image
I am currently unable to solve these 2. Please guide me on this

### CODE REVIEW

**Comment by aaryan2134** [comment]
Please let me know what changes should I make
Thank you!

**Review by stnguyen90 — CHANGES_REQUESTED** [review]
You need to add additional typing for those variables:

>   12     Property Utopia\Domains\Domain::$list type has no value type specified in iterable type array.   

```php
    /**
     * @var array<string, array{suffix: string, type: string, comments: string[]}> $list
     */
    static protected $list = [];
```

>   54     Property Utopia\Domains\Domain::$parts type has no value type specified in iterable type array. 

```php
    /**
     * Domain Parts
     *
     * @var string[]
     */
    protected $parts = [];
```

**Comment by aaryan2134** [comment]
image
Made the changes. Now no errors being shown
Thanks for the help!

**Review by stnguyen90 — APPROVED** [review]
Awesome work on your PR! We've approved your work and it'll be merged soon!

**Comment by christyjacob4** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)

**Pull request merged**
